# Generated by Django 3.0.8 on 2020-08-03 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tv_app', '0002_auto_20200803_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasoncopy',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='all_season_copies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
