# Generated by Django 3.0.2 on 2020-01-31 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('release_year', models.IntegerField(verbose_name='Release Year')),
                ('mpaa_rating', models.CharField(max_length=4, verbose_name='MPAA Rating')),
                ('run_time_minutes', models.IntegerField(verbose_name='Run Time (mins)')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200, verbose_name='Platform')),
                ('form', models.CharField(max_length=200, verbose_name='Format')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='movie_app.Movie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_copies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
