# Generated by Django 3.0.2 on 2020-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='run_time_minutes',
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime_minutes',
            field=models.IntegerField(default=120, verbose_name='Runtime (mins)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(max_length=5, verbose_name='MPAA Rating'),
        ),
    ]
