# Generated by Django 3.0.2 on 2020-01-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_time_minutes',
            field=models.IntegerField(),
        ),
    ]
