# Generated by Django 3.0.3 on 2020-02-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecopy',
            name='vod_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VOD Link'),
        ),
    ]
