# Generated by Django 3.0.3 on 2020-02-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_moviecopy_vod_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_page_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='TMDB Page Link'),
        ),
    ]
