# Generated by Django 3.0.2 on 2020-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20200117_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mpaa_rating',
            field=models.CharField(max_length=4, verbose_name='MPAA Rating'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='run_time_minutes',
            field=models.IntegerField(verbose_name='Run Time (mins)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
