# Generated by Django 3.0.3 on 2020-02-22 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_tmdb_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Image Link'),
        ),
    ]
