# Generated by Django 3.0.3 on 2020-02-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20200222_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='Overview'),
        ),
    ]
