# Generated by Django 3.0.2 on 2020-01-22 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=200, verbose_name='Platform')),
                ('form', models.CharField(max_length=200, verbose_name='Format')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='movie_app.Movie')),
            ],
        ),
    ]
